# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjJjYjQ0ZTAzMDBiY2M1YWM1MzYyOWVjYmYzNzMyZWIwMGMxNDk0MjhmOWZlMDIwZThhN2JlNTIxM2U4NDExZGE1YzFlNmIxYWJhNjUxMWJkNzg5ZDdiMGQ3MWM2NWYxOGViZDA2ZjE2OGMzNjZhYjM1ZThkNzAyZTBiMTY0YmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
